### PR TITLE
Revise and update CMakeLists.txt to directly use the spglib github repository.

### PR DESCRIPTION
**Pull request by hongyi-zhao**
Revise and update CMakeLists.txt to directly use the spglib GitHub repository. See https://github.com/spglib/spglib/issues/418 for the related discussion.

### CODE REVIEW

**Comment by LecrisUT** [comment]
About your last question about CLI, you can try building with `BUILD_CGI`.

**Comment by hongyi-zhao** [comment]
```shell
$ mkdir build
$ cd build
$ cmake .. -DBUILD_CGI=ON
$ cmake --build . -j44
$ ls
CMakeCache.txt  CMakeFiles  cmake_install.cmake  _deps  libXtalComp.a  libXtalComp.so  Makefile  test  xtalcomp.cgi
$ ./xtalcomp.cgi ~/Desktop/temp/异质结文件/C12H14Mg7N6O14_18.00_degree_0.vasp  ~/Desktop/temp/异质结文件/C12H14Mg7N6O14_19.00_degree_0.vasp 
Segmentation fault (core dumped)

```
So, I still don't know how to use `xtalcomp.cgi` locally?

**Comment by LecrisUT** [comment]
:shrug: Not familiar with cgi. Probably not a proper cli by the look of the code.

You might need to consider what kind of CLI interface you want, or if it would be more convenient to have a binding to another language like we do for python in spglib.

**Comment by hongyi-zhao** [comment]
>You might need to consider what kind of CLI interface you want, 

I mean, just as any *nix utilities, say, sed, grep, awk, etc.

>or if it would be more convenient to have a binding to another language like we do for python in spglib.

Agreed.

**Comment by LecrisUT** [comment]
> I mean, just as any *nix utilities, say, sed, grep, awk, etc.

Would be tricky because what is the input/output to the cli, what is the data format etc.

But anyway can open an issue if you are interested in some designs for either cli or making a python interface. For here, let's see if the devs come back to this, what the future plan for this project is and other maintenance.

**Comment by hongyi-zhao** [comment]
To be frank, as for the future of this project, perhaps I am more optimistic about the professional or systematic implementation in [pymatgen](https://github.com/materialsproject/pymatgen/issues/3597#issuecomment-1920510020) or [CARAT](https://github.com/lbfm-rwth/carat).

**Comment by alliepiper** [comment]
Thanks for the contribution, it looks reasonable to me and I've confirmed the tests pass. I'll merge this in a moment.

> For here, let's see if the devs come back to this, what the future plan for this project is and other maintenance.

XtalComp is very much unmaintained at this point. It was a grad school project that was released open-source as a reference implementation to support a publication, but I no longer work in crystallography or have interest in continuing development in this area.

I'd happily pass ownership over to someone interested in taking over maintenance as long as the open-source nature of the project is not changed. I don't mind reviewing (minor) patches like this one in the meantime, but anything more involved would not be feasible for me at this time. Forks / reimplementations are also fine with me.

**Pull request merged**
