### PR TITLE
Fix issue with overlapping atoms after wrapping.

### PR DESCRIPTION
**Pull request by alliepiper**
This is a combination of 3 commits.

The first commit's message is:
Update xtalcomp.cpp

This is the 2nd commit message:

Update xtalcomp.h

This is the 3rd commit message:

Update test.cpp

Author:    psavery saintpatrick3@gmail.com

### CODE REVIEW

**Comment by alliepiper** [comment]
Thanks Patrick!

I squashed them together, since it's ideal to leave every commit in a compilable state. It makes using `git bisect` to find bugs easier, and it's just a nice way to group changes :)

I'm spotted a couple of small issues I wanted to address, but I'll push the cleanups on this branch so you can see them. Feel free to ask questions if something doesn't make sense!

**Comment by alliepiper** [comment]
@psavery All merged in :+1:

I tried to give reasons in the commit messages for why I made the changes I did, so that's why they're so long....The only major tweak I did was replace the XcVector with different datatype. 

If you get a chance, can you rerun the XtalOpt test / benchmark on this? I'm curious how it compares to your earlier tests, and my XtalOpt build is long, long gone ;) The map might actually have slowed things down a bit...after looking more closely at your implementation, I realize it may not be the best choice (I thought there would be more keyed random accesses into it).

Also, if you can push a pull request to the XtalOpt github repository to update the version it uses that'd be awesome :D

**Comment by psavery** [comment]
Hey Dave! I just submitted another request to remove a couple more lines (it wouldn't compile with XTALCOMP_DEBUG). 

As for XtalOpt: we are planning to release a new version within the next two weeks. I'll make sure you get it if you want it! It mostly consists of a few additions Zack made.

New times: Success time: 1712 ms total (0.6848 ms average), Failure time: 4669 ms total (1.8676 ms average) compared to what it was with just my changes: success time: 1676 ms total (0.6704 ms average), failure time: 5057 ms total (2.0228 ms average). So it looks like it is faster with the map!

Original xtalcomp times: Success time: 1765 ms total (0.706 ms average), failure time: 4595 ms total (1.838 ms average).

I also found out how to get vim to remove all trailing white space automatically upon saving, so hopefully that will be fine now! I may try to look for a new text editor (or IDE) sooner or later, though...

I really appreciate the comments you left me. They're helpful for sure as I try to make my coding better. Seeing some of those functions like std::map and std::pair is useful for me as well! I may want to use them sometime in the future.

By the way, random question: I noticed that you prefix m_ behind some class variables. I've kinda been following suite. I was wondering what that means, though?

Thank you very much for all you help! I really do appreciate it.

Patrick

**Comment by alliepiper** [comment]
Cool, thanks for running the timings -- that looks fine to me.

As for IDEs, I use QtCreator. It has QtDesigner built in, so working on GUIs is easy, and is an all-around solid IDE with a lot of nice features.

The `m_` prefix is for "member" variables of a class. It helps with readability to know whether a variable is a member of the class or a temporary variable in a function's scope. It's just a convention used by a lot of the projects I work on -- other projects have different conventions (for instance, VTK capitalizes member variables, but not local variables).

BTW, The XtalComp class is really a poor example of a good class design -- I wrote it to be a simple interface that hides a lot of complexity, so there are weird things going on in it...like how most of the work is done by static functions in the cpp file.

Great to hear about the new XtalOpt -- I'll be glad to review/merge in some pull requests when we get to that point.

**Pull request merged**
